version: '3.5'

services:
  jupyter-all-spark:
    Image: cyb3rward0g/jupyter-all-spark:0.0.1
    container_name: jupyter-all-spark
    environment:
      JUPYTER_TYPE: lab
      JUPYTER_BASE_URL: /jupyter
    ports:
      - "8888:8888"
    restart: always
    networks:
      hunting:

networks:
  hunting:
    driver: bridge

volumes:
  notebooks:
    driver: local