version: '3.5'

services:
  jupyter-hunt:
    image: cyb3rwardog/jupyter-hunt:0.0.7
    container_name: jupyter-hunt
    volumes:
      - notebooks:/opt/jupyter/notebooks
    environment:
      JUPYTER_TYPE: lab
      JUPYTER_BASE_URL: /jupyter
    ports:
      - "8888:8888"
    restart: always
    networks:
      hunting:

networks:
  hunting:
    driver: bridge

volumes:
  notebooks:
    driver: local
